// Plot total production (sum of both line0 and line1)
from(bucket: "high_rate")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["source"] == "power-meter")
  |> filter(fn: (r) => r["measurement-type"] == "production")
  |> filter(fn: (r) => r["_field"] == "P")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> group(columns: ["_time"], mode:"by")
  |> sum(column: "_value")
  |> group()
  |> yield()
