FROM debian:bullseye-slim

# Install Stuff
RUN apt update
RUN apt -y install python3 python3-pip git
RUN python3 -m pip install -U git+https://github.com/amykyta3/enphase-power-logger

ENV ENPHASE_EMAIL=name@example.com
ENV ENPHASE_PASSWORD=password
ENV ENVOY_SERIAL=123456789123
ENV INFLUXDB_URL=http://localhost:8086
ENV INFLUXDB_TOKEN=XXX
ENV INFLUXDB_ORG=home
ENV INFLUXDB_BUCKET_HR=high_rate
ENV INFLUXDB_BUCKET_LR=low_rate

# entrypoint
CMD python3 -m power_logger
