FROM debian:bullseye-slim

ADD https://raw.githubusercontent.com/amykyta3/enphase-power-logger/main/launcher.sh /
RUN chmod +x /launcher.sh

# Install Stuff
RUN apt update
RUN apt -y install python3 python3-pip git

ENV ENPHASE_EMAIL=name@example.com
ENV ENPHASE_PASSWORD=password
ENV ENVOY_SERIAL=123456789123
ENV INFLUXDB_URL=http://localhost:8086
ENV INFLUXDB_TOKEN=XXX
ENV INFLUXDB_ORG=home
ENV INFLUXDB_BUCKET_HR=high_rate
ENV INFLUXDB_BUCKET_LR=low_rate

# entrypoint
CMD /launcher.sh
